[package]
name = "resonance"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
esp32 = []

[target.'cfg(not(target_arch = "xtensa"))'.dependencies]
spin = { workspace = true, features = ["spin_mutex"] }
x86_64 = { workspace = true, features = [
  "instructions",
] }

[target.'cfg(target_arch = "xtensa")'.dependencies]
spin = { workspace = true, features = ["spin_mutex"] }
