[workspace]
members = [
  "bellows",
  "flasks",
  "fullerene-kernel", "petroleum",
  "toluene",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
