# [package]
# name = "fullerene"
# version = "0.1.0"
# edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "bellows", "flasks", "fullerene-kernel",
  "toluene",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
