use std::fmt::Write;

pub const RULE_FILE_NAME: &str = "70-fullerene-adb.rules";

#[derive(Clone, Copy)]
struct UsbIdentity {
    vendor_id: u16,
    product_id: u16,
    description: &'static str,
}

const IDENTITIES: [UsbIdentity; 2] = [
    UsbIdentity {
        vendor_id: 0x1234,
        product_id: 0x0001,
        description: "temporary FullereneOS debug identity",
    },
    UsbIdentity {
        vendor_id: 0x18d1,
        product_id: 0x4ee7,
        description: "stock Pixel 4a (5G) identity",
    },
];

/// Render the deployment artifact consumed by udev.
///
/// The source of truth is Rust; `.rules` is only the output format required
/// by the host's udev rule loader.
pub fn render() -> String {
    let mut rules = String::from(
        "# Generated by `flasks udev-rules`; do not edit by hand.\n".to_owned()
            + "# FullereneOS development transport.\n"
            + "# Both identities are retained so a controlled return to the\n"
            + "# bootloader does not lose access to the device node.\n",
    );
    for identity in IDENTITIES {
        writeln!(rules, "# {}", identity.description,).expect("writing to a String cannot fail");
        writeln!(
            rules,
            "SUBSYSTEM==\"usb\", ATTR{{idVendor}}==\"{:04x}\", ATTR{{idProduct}}==\"{:04x}\", MODE=\"0660\", GROUP=\"plugdev\", TAG+=\"uaccess\", ENV{{adb_user}}=\"yes\"",
            identity.vendor_id,
            identity.product_id,
        )
        .expect("writing to a String cannot fail");
    }
    rules
}
