[workspace]

[package]
name = "viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false, features = [
    "jpeg", "png", "bmp", "gif", "qoi",
] }
mp4 = "0.14"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }

[dev-dependencies]
z264 = { version = "0.1.0", default-features = false }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
