# fullerene-kernel/Cargo.toml
[package]
name = "fullerene-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = { version = "0.15.2", default-features = false, features = ["instructions"] }
spin = { version = "0.10.0", default-features = false, features = ["once", "mutex", "spin_mutex"] }
bitflags = { version = "2.3.2", default-features = false }

[profile.dev]
debug = true
split-debuginfo = "packed"
