[package]
name = "fullerene-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = { version = "0.10.0", default-features = false, features = ["once"] }
# The bootloader should be a regular dependency, not a build-dependency.
bootloader = { version = "0.11.12", features = ["bios"], default-features = false }

[profile.dev]
panic = "abort"
# Omit the build-std flags in the Cargo.toml file.
# They are typically passed as command-line arguments.
# For example: cargo build -Z build-std=core,compiler_builtins

[profile.release]
panic = "abort"

# The `[package.metadata.bootloader.target]` section is not used in modern bootloader versions.
# The `bootloader` crate automatically determines the target based on the build command.