[package]
name = "fullerene-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = { version = "0.11.12", default-features = false, features = ["uefi"] }
spin = "0.10.0"

[build-dependencies]
bootloader = { version = "0.11.12", default-features = false, features = ["uefi"] }
