# fullerene-kernel/Cargo.toml
[package]
name = "fullerene-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = { version = "0.15.2", default-features = false, features = [
  "instructions",
  "abi_x86_interrupt",
] }
spin = { version = "0.10.0", default-features = false, features = [
  "once",
  "mutex",
  "spin_mutex",
] }
lazy_static = { version = "1.5.0", default-features = false, features = [
  "spin_no_std",
] }

petroleum = { path = "../petroleum" }

[profile.dev]
debug = true
split-debuginfo = "packed"

[profile.release]
debug = true
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
