[package]
name = "nitrogen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
esp32 = []

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { workspace = true, features = [
  "instructions",
] }
spin = { workspace = true, features = [
  "once",
  "spin_mutex",
] }
log = { workspace = true }
ps2-mouse = { git = "https://github.com/rust-osdev/ps2-mouse", rev = "68803c8dba7c2008eb3b95c47452d51305227ff" }
bonder = { path = "../bonder" }
sealant = { path = "../sealant" }

[lib]
name = "nitrogen"
path = "src/lib.rs"
crate-type = ["lib"]

[target.'cfg(target_arch = "xtensa")'.dependencies]
spin = { workspace = true, features = ["spin_mutex"] }
log = { workspace = true }
