cargo-features = ["profile-rustflags"]

[package]
name = "bellows"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bellows"
path = "src/main.rs"

[features]
debug_loader = []

[profile.dev]
panic = "abort"
rustflags = ["-C", "target-feature=-red-zone"]

[profile.release]
codegen-units = 1
rustflags = ["-C", "target-feature=-red-zone"]
panic = "abort"

[dependencies]
linked_list_allocator = "0.10.5"
spin = "0.10.0"
petroleum = { path = "../petroleum" }
x86_64 = { version = "0.15.2", default-features = false, features = ["instructions"] }
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
