[package]
name = "bellows"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "bellows"
path = "src/main.rs"
test = false
bench = false

[[bin]]
name = "bellows-esp32"
path = "src/arch/xtensa/main.rs"
required-features = ["esp32"]
test = false
bench = false

[target.'cfg(not(target_arch = "xtensa"))'.dependencies]
linked_list_allocator = "0.10.6"
spin = { workspace = true, features = ["mutex", "spin_mutex"] }
petroleum = { path = "../petroleum" }
fullerene-abi = { path = "../fullerene-kernel/abi" }
x86_64 = { workspace = true, features = ["instructions"] }
log = { workspace = true }

[target.'cfg(target_arch = "xtensa")'.dependencies]
fullerene-kernel = { path = "../fullerene-kernel", features = ["esp32"] }

[features]
debug_loader = []
esp32 = []
