[package]
name = "bellows"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]  # Notes: PE/COFF (EFI)

[dependencies]
linked_list_allocator = "0.10.5"
uefi = "0.35.0"
uefi-raw = "0.11.0"
uefi-macros = "0.18.1"
uefi-services = "0.26.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
