[package]
name = "bellows"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bellows"
path = "src/main.rs"

# [lib]
# crate-type = ["cdylib"]  # Notes: PE/COFF (EFI)

[dependencies]
linked_list_allocator = "0.10.5"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[build-dependencies]
compiler_builtins = { version = "0.1.160", default-features = false, features = ["no-asm"] }
