[package]
name = "bellows"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]  # Notes: PE/COFF (EFI)

[dependencies]
linked_list_allocator = "0.10.5"
uefi = { version = "0.35.0", default-features = false, features = ["alloc"] }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
