//! 8×16 fixed‑width bitmap font.
//!
//! Glyph data is embedded from a binary generated by `build.rs` at compile
//! time.  The binary contains 95 glyphs × 16 bytes each in row‑major order
//! (MSB = leftmost pixel).
//!
//! To update the font data: edit `build.rs` and rebuild.

pub const GLYPH_WIDTH: u32 = 8;
pub const GLYPH_HEIGHT: u32 = 16;
pub const GLYPH_BYTES: usize = 16;
pub const GLYPH_COUNT: usize = 95;

/// Raw font bitmap — 95 glyphs × 16 bytes each = 1520 bytes.
static FONT_BIN: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/font8x16.bin"));

pub struct Glyph<'a> {
    rows: &'a [u8],
}

impl Glyph<'_> {
    #[inline]
    pub fn pixel(&self, row: u32, col: u32) -> bool {
        let byte = self.rows[row as usize];
        byte & (0x80 >> col) != 0
    }
}

/// Look up a glyph for printable ASCII (0x20–0x7E).  Others → space.
#[inline]
pub fn glyph(ch: u8) -> Glyph<'static> {
    let idx = if ch >= 0x20 && ch <= 0x7E {
        (ch - 0x20) as usize
    } else {
        0
    };
    let start = idx * GLYPH_BYTES;
    Glyph { rows: &FONT_BIN[start..start + GLYPH_BYTES] }
}

#[inline]
pub fn get_glyph_pixel(ch: u8, row: u32, col: u32) -> bool {
    glyph(ch).pixel(row, col)
}