#!/usr/bin/env python3
"""Generate docs/SUPPORT_MATRIX.md from support/matrix.toml."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "support" / "matrix.toml"
OUTPUT = ROOT / "docs" / "SUPPORT_MATRIX.md"
STATUS = {
    "Full": "✅ Full",
    "Partial": "🟡 Partial",
    "Stub": "🧩 Stub",
    "NotSupported": "❌ Not supported",
}


def render_cell(value: str) -> str:
    return STATUS.get(value, value).replace("|", r"\|")


def generate() -> str:
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [
        f"# {data['title']}",
        "",
        "<!-- Generated by scripts/generate_support_matrix.py; edit support/matrix.toml. -->",
        "",
    ]
    for section in data["section"]:
        columns = section["columns"]
        rows = section["rows"]
        if any(len(row) != len(columns) for row in rows):
            raise ValueError(f"{section['title']}: row width does not match columns")
        lines.extend(
            [
                f"## {section['title']}",
                "",
                "| " + " | ".join(columns) + " |",
                "|" + "|".join("---" for _ in columns) + "|",
            ]
        )
        lines.extend(
            "| " + " | ".join(render_cell(cell) for cell in row) + " |"
            for row in rows
        )
        lines.append("")
    lines.extend(
        [
            "Status values are generated from the same TOML data checked by CI.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            print(
                "docs/SUPPORT_MATRIX.md is stale; run "
                "python scripts/generate_support_matrix.py",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
