[package]
name = "solvent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
x86_64 = { workspace = true, features = [
  "instructions",
] }
spin = { workspace = true, features = [
  "once",
  "mutex",
  "spin_mutex",
] }
bonder = { path = "../bonder" }
petroleum = { path = "../petroleum" }
nitrogen = { path = "../nitrogen" }
carrier = { path = "../carrier" }
nozzle = { path = "../nozzle" }
lattice = { path = "../lattice" }
resonance = { path = "../resonance" }
chronoline = { path = "../chronoline" }
genome = { path = "../genome" }
log = { workspace = true }

[lib]
name = "solvent"
path = "src/lib.rs"

[dev-dependencies]
petroleum = { path = "../petroleum", features = ["std"] }
