[package]
name = "petroleum"
version = "0.1.0"
edition = "2024"

[features]
default = []
std = []
vga_panic = []

[dependencies]
spin = { version = "0.10.0", default-features = false, features = [
  "once",
  "mutex",
  "spin_mutex",
] }
x86_64 = { version = "0.15.2", default-features = false, features = [
  "instructions",
  "abi_x86_interrupt",
] }
linked_list_allocator = "0.10"

[lib]
name = "petroleum"
path = "src/lib.rs"
