name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cargo-criterion
        run: cargo +nightly install cargo-criterion --locked

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./ -> target"

      - name: Run benchmarks for toluene
        run: cargo +nightly criterion --package toluene -- --output-format=bencher

      - name: Run benchmarks for flasks (if any)
        run: cargo +nightly criterion --package flasks -- --output-format=bencher || echo "No benchmarks in flasks"

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion/
          retention-days: 30

  compare:
    name: Compare Benchmarks
    runs-on: ubuntu-latest
    needs: benchmark
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion/

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Cargo Benchmark
          tool: 'cargo'
          output-file-path: target/criterion/index.html
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: '200%'
