name: Dependency Check

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cargo-audit
        run: cargo +nightly install cargo-audit --locked

      - name: Run security audit
        run: cargo audit

  outdated:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cargo-outdated
        run: cargo +nightly install cargo-outdated --locked

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1 --workspace
        continue-on-error: true # Don't fail the build, just report
